### ISSUE TITLE
Threatening language at odds with intended nature of this letter.

### ISSUE THREAD

**Issue by rewtd** [owasp-change/owasp-change.github.io#78]
I realise that changing the text of the letter after so many have signed is impossible. But a lot is being said about the text "if not addressed immediately, will result in important projects, like ours, leaving OWASP" which many perceive to be a threat. If it is a threat then I definitely do not endorse that and it absolutely runs at odds with the "with positive intent" and "in the best interests of the OWASP community" parts of the letter which I whole-heartedly endorse.

**Comment by psiinon** [comment]
The intent of the letter was, I believe, to focus minds - I think it has done that 😁 
You can choose to read it as a threat or a prediction, or however you choose.
TBH I would now much rather focus on how we solve the issues raised by this letter.
It is clear that the projects want and need things to change.
How do we make that happen, quickly, but without compromising what we stand for?

**Comment by kingthorin** [comment]
Of course people can and will interpret it in different ways. Any individual sentence can be contextualized a bunch of different ways. In this case it’s important to absorb the “We don’t want that to happen.” immediately following the sentence you’re talking about.

It’s also easy to nitpick from the outside looking in after the fact. I even see parts that might be worded differently at this point. Hind sight being 20/20 as they say.

**Comment by streetchief** [comment]
If you don't fund projects, they tend to disappear for lack of money.

**Comment by rewtd** [comment]
What @streetchief said is true. But I'm not threatening OWASP to take my toys and leave. I guess the point of the letter (as @psiinon put it) was to spur action. Not stir up dissent or to give up who we are.

**Comment by rewtd** [comment]
I believe that @kingthorin has hit the nail on the head here. It can be read as you choice to read it. I chose to read the positives only.
